fix: tsam version compability (#2266)
* Set temporal resolution to segments in test

* fix[tsam<3.0]: import error

After `import tsam` the expression `tsam.timeseriesaggregation`did't resolve properly.

* bumb: tsam>=3.0

* fix[tsam>=3.0]: unexpected keyword

TypeError: aggregate() got an unexpected keyword argument 'solver'

* fix[tsam>=3.0]: attribute error

AttributeError: 'AggregationResult' object has no attribute 'createTypicalPeriods'

* Revert "bumb: tsam>=3.0"

This reverts commit 56831fa476dbaed1548b851de32dd56bcccea39a.

* Revert "Set temporal resolution to segments in test"

This reverts commit f00214bafad359f1e75ffc4bb9d6d923003ce1d3.